server:
  port: 8001
  
#mybatis配置
#mybatis配置文件  
mybatis:
  config-location: classpath:mybatis/mybatis.xml        # mybatis配置文件所在路径
  type-aliases-package: com.andy.model    # 所有Entity别名类所在包
  mapper-locations:
     - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
#Spring的应用名  
spring:
   application:
    name: andy-prorider 
#Spring数据库连接
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8             # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka10100.com:10100/eureka,http://eureka10101.com:10101/eureka,http://eureka10102.com:10102/eureka
  instance:
    instance-id: haode
    prefer-ip-address: true
    
info:
  app.name: gaosheng
  company.name: 杰克
  build.artifactId: $project.artifactId$   
  build.version: $project.version$        